name: 'Deploy to AWS S3' # about learn more : https://docs.github.com/en/actions/tutorials/create-actions/create-a-javascript-action
description: 'Deploy a static website via AWS S3.'
runs:
  using: 'node16'
  main: 'main.js'