name: 'Get & Cache Dependences'
description: 'Get the dependencies ( via npm ) and cache them.'
runs:
  using: 'composite' # https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash